// Card ingestion pipeline — normalizer + validator.
// Input: raw optcgapi JSON (array). Output: normalized card objects + validation report.
// Production flow: scripts/ingest/fetch.js → normalize() → diff against registry →
// write src/data/<set>.cards.js + report (new / updated / errata / alt-art / invalid).

const COLORS = ["Red", "Green", "Blue", "Purple", "Black", "Yellow"];
const CATEGORIES = ["Leader", "Character", "Event", "Stage", "DON!!"];
const ATTRIBUTES = ["Slash", "Strike", "Ranged", "Special", "Wisdom", null];

const nn = v => (v == null || v === "NULL" || v === "" ? null : v);
const num = v => (nn(v) == null ? null : parseInt(v, 10));

export function normalizeCard(raw) {
  const errors = [];
  const code = nn(raw.card_set_id);
  if (!code || !/^[A-Z0-9]+-\d{3}/.test(code)) errors.push(`bad code: ${raw.card_set_id}`);
  const category = nn(raw.card_type);
  if (!CATEGORIES.includes(category)) errors.push(`bad category: ${category}`);
  const colors = (nn(raw.card_color) || "").split(/[/\s]+/).map(s => s.trim()).filter(Boolean);
  if (!colors.length || !colors.every(c => COLORS.includes(c))) errors.push(`bad colors: ${raw.card_color}`);
  const attribute = nn(raw.attribute);
  // newer cards can carry two attributes (e.g. "Special Strike"); accept if every token is valid
  const attrOk = attribute == null || attribute.split(/[/\s]+/).every(a => ATTRIBUTES.includes(a));
  if (!attrOk) errors.push(`bad attribute: ${attribute}`);

  // text: split [Trigger] clause out; strip scraper annotations; flag errata
  let text = nn(raw.card_text), triggerText = null, errata = false;
  if (text) {
    if (/officially errata'd/i.test(text)) { errata = true; text = text.replace(/\s*This card has been officially errata'd\.?/i, ""); }
    const t = text.match(/\[Trigger\]\s*(.+)$/s);
    if (t) { triggerText = t[1].trim(); text = text.slice(0, t.index).trim() || null; }
  }
  const card = {
    code, name: nn(raw.card_name)?.replace(/\s*\(\d+\)$/, ""), category, colors,
    cost: num(raw.card_cost), power: num(raw.card_power),
    counter: raw.counter_amount == null ? null : num(raw.counter_amount),
    life: num(raw.life), attribute,
    types: (nn(raw.sub_types) || "").split(/\s{1,}/).join(" ").split(" ").length
      ? splitTypes(nn(raw.sub_types)) : [],
    rarity: nn(raw.rarity), set: nn(raw.set_id),
    text, triggerText, errata,
    image: nn(raw.card_image), i18n: {},
  };
  // structural checks
  if (card.category === "Leader" && card.life == null) errors.push("leader without life");
  if (card.category === "Character" && card.power == null) errors.push("character without power");
  if (card.category !== "Leader" && card.cost == null) errors.push("non-leader without cost");
  return { card, errors };
}

// optcgapi packs multi-word types space-separated; resolve against a known-type lexicon
// so "Fish-Man Straw Hat Crew" → ["Fish-Man","Straw Hat Crew"].
const MULTIWORD = ["Straw Hat Crew", "Whitebeard Pirates", "Kid Pirates", "Heart Pirates",
  "Bonney Pirates", "On-Air Pirates", "Hawkins Pirates", "Firetank Pirates", "Drake Pirates",
  "Fallen Monk Pirates", "Baroque Works", "Donquixote Pirates", "Big Mom Pirates",
  "Beasts Pirates", "Red-Haired Pirates", "Blackbeard Pirates", "Revolutionary Army",
  "Land of Wano", "The Seven Warlords of the Sea", "Whitebeard Pirates Allies",
  "Former Whitebeard Pirates", "Straw Hat Crew Allies"];
export function splitTypes(s) {
  if (!s) return [];
  const out = [];
  let rest = s.trim();
  while (rest.length) {
    const hit = MULTIWORD.find(m => rest.startsWith(m));
    if (hit) { out.push(hit); rest = rest.slice(hit.length).trim(); }
    else {
      const sp = rest.indexOf(" ");
      if (sp === -1) { out.push(rest); rest = ""; }
      else { out.push(rest.slice(0, sp)); rest = rest.slice(sp + 1).trim(); }
    }
  }
  return out;
}

// Diff a normalized batch against the existing registry.
export function diffAgainstRegistry(batch, registry) {
  const report = { added: [], updated: [], errata: [], altArt: [], unchanged: [], invalid: [] };
  for (const { card, errors } of batch) {
    if (errors.length) { report.invalid.push({ code: card.code, errors }); continue; }
    // alt-art: same base code with suffix (e.g. OP01-001_p1) or duplicate code+different image
    const base = registry.get(card.code);
    if (!base) report.added.push(card.code);
    else if (base.text !== card.text || base.triggerText !== card.triggerText) {
      (card.errata ? report.errata : report.updated).push(card.code);
    } else if (base.image !== card.image) report.altArt.push(card.code);
    else report.unchanged.push(card.code);
  }
  return report;
}

export function emitModule(setVar, cards) {
  return `// AUTO-GENERATED by scripts/ingest — real data from optcgapi.com. Do not hand-edit stats.\n` +
    `export const ${setVar} = ${JSON.stringify(cards, null, 1)};\n`;
}
